name: waterproof mascara
favicon: null
layout_spectrum: 0.67062
typography_spectrum: 0.41321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12262d'
    - '#aab7b0'
    - '#88938f'
    - '#426662'
    - '#e5e4e0'
  brandStrength: 0
  lightness: 0.41950855078175664
  saturation: 0.5735619750339538
  rhythmicContrast: 0.5479412036947906
purpose: []
